# Done by: Khalid Mosad

#PaymentSys.exe Target Binary
# Prerequisite  Files: PaymentSystem.c PaymentSystem_int.h main.c Types.h
PaymentSys.exe: PaymentSystem.c PaymentSystem_int.h main.c Types.h
	gcc PaymentSystem.c  main.c -o PaymentSys.exe -std=c99 -g
